"""from collections import namedtuple

# Define the namedtuple type
Keyword = namedtuple("Keyword", ["phrase", "weight"])

# Define the specialization with 5 key phrases
specializationData = {
    "Artificial Intelligence": [
        Keyword("AI Product Manager", 1.0),
        Keyword("Deep Learning", 0.9),
        Keyword("Neural Networks", 0.8),
        Keyword("Explainable AI", 0.5),
        Keyword("Patent Filing", 0.1),
    ]
}"""

from collections import namedtuple

Keyword = namedtuple("Keyword", ["phrase", "weight"])

specializationData = {
    "Artificial Intelligence": [
        # Core AI concepts and techniques (1.0)
        Keyword("Artificial Intelligence", 1.0),
        Keyword("AI", 1.0),
        Keyword("Machine Learning", 1.0),
        Keyword("Deep Learning", 1.0),
        Keyword("Neural Networks", 1.0),
        Keyword("Natural Language Processing", 1.0),
        Keyword("Computer Vision", 1.0),
        Keyword("Reinforcement Learning", 1.0),
        Keyword("Transformers", 1.0),
        Keyword("Generative Adversarial Networks", 1.0),
        Keyword("GANs", 1.0),
        Keyword("Convolutional Neural Networks", 1.0),
        Keyword("CNN", 1.0),
        Keyword("Recurrent Neural Networks", 1.0),
        Keyword("RNN", 1.0),
        Keyword("Long Short-Term Memory", 1.0),
        Keyword("LSTM", 1.0),
        Keyword("BERT", 1.0),
        Keyword("GPT", 1.0),
        Keyword("OpenAI", 1.0),
        Keyword("Attention Mechanism", 1.0),
        Keyword("Seq2Seq", 1.0),
        Keyword("Sequence-to-Sequence Models", 1.0),
        Keyword("AI Ethics", 0.9),
        Keyword("Explainable AI", 0.9),
        Keyword("XAI", 0.9),
        Keyword("AI Research", 0.9),
        Keyword("AI Strategy", 0.9),
        Keyword("Meta-Learning", 0.9),
        Keyword("Federated Learning", 0.9),
        Keyword("Active Learning", 0.8),
        Keyword("Self-Supervised Learning", 0.8),

        # Popular AI Frameworks & Libraries (0.9 - 1.0)
        Keyword("TensorFlow", 1.0),
        Keyword("PyTorch", 1.0),
        Keyword("Keras", 0.95),
        Keyword("scikit-learn", 0.95),
        Keyword("Hugging Face Transformers", 0.95),
        Keyword("FastAI", 0.85),
        Keyword("Caffe", 0.8),
        Keyword("MXNet", 0.8),
        Keyword("Theano", 0.7),
        Keyword("ONNX", 0.7),
        Keyword("TorchServe", 0.7),
        Keyword("Detectron2", 0.85),
        Keyword("OpenCV", 0.85),
        Keyword("SpaCy", 0.9),
        Keyword("NLTK", 0.85),
        Keyword("Gensim", 0.75),

        # Programming Languages (0.2 - 0.5)
        Keyword("Python", 0.5),
        Keyword("R", 0.35),
        Keyword("C++", 0.35),
        Keyword("Java", 0.3),
        Keyword("Julia", 0.25),
        Keyword("MATLAB", 0.25),
        Keyword("Scala", 0.2),

        # Data Handling, Big Data, and Databases (0.3 - 0.6)
        Keyword("SQL", 0.4),
        Keyword("NoSQL", 0.3),
        Keyword("MongoDB", 0.35),
        Keyword("Apache Hadoop", 0.4),
        Keyword("Apache Spark", 0.5),
        Keyword("Kafka", 0.4),
        Keyword("Data Lakes", 0.35),
        Keyword("ETL", 0.3),
        Keyword("Data Pipelines", 0.45),

        # Cloud & MLOps Platforms (0.5 - 0.7)
        Keyword("AWS SageMaker", 0.7),
        Keyword("Google AI Platform", 0.7),
        Keyword("Azure Machine Learning", 0.7),
        Keyword("Kubeflow", 0.6),
        Keyword("MLflow", 0.6),
        Keyword("TensorBoard", 0.6),
        Keyword("Docker", 0.5),
        Keyword("Kubernetes", 0.5),
        Keyword("Airflow", 0.5),
        Keyword("DVC", 0.5),

        # Important AI concepts & techniques (0.7 - 0.9)
        Keyword("Feature Engineering", 0.9),
        Keyword("Hyperparameter Tuning", 0.9),
        Keyword("Model Deployment", 0.85),
        Keyword("MLOps", 0.85),
        Keyword("Data Science", 0.75),
        Keyword("Big Data", 0.65),
        Keyword("Data Mining", 0.6),
        Keyword("Dimensionality Reduction", 0.7),
        Keyword("Clustering", 0.75),
        Keyword("Classification", 0.8),
        Keyword("Regression", 0.7),
        Keyword("Predictive Modeling", 0.75),
        Keyword("Anomaly Detection", 0.75),
        Keyword("Bayesian Inference", 0.65),
        Keyword("Optimization", 0.7),
        Keyword("Gradient Descent", 0.75),
        Keyword("Convex Optimization", 0.7),
        Keyword("Linear Algebra", 0.7),
        Keyword("Calculus", 0.6),
        Keyword("Numerical Methods", 0.6),

        # Specialized AI fields (0.7 - 1.0)
        Keyword("Robotics", 0.7),
        Keyword("Autonomous Vehicles", 0.7),
        Keyword("SLAM", 0.7),
        Keyword("Robot Operating System", 0.7),
        Keyword("Speech Recognition", 0.8),
        Keyword("Optical Character Recognition", 0.7),
        Keyword("Face Recognition", 0.8),
        Keyword("Video Analytics", 0.7),

        # AI-related roles (0.5 - 0.8)
        Keyword("AI Product Manager", 0.8),
        Keyword("Data Scientist", 0.8),
        Keyword("AI Research Scientist", 0.9),
        Keyword("Applied Scientist", 0.85),
        Keyword("MLOps Engineer", 0.75),
        Keyword("Research Engineer", 0.8),

        # Soft and ethical AI topics (0.5 - 0.9)
        Keyword("Responsible AI", 0.85),
        Keyword("Ethical AI", 0.85),
        Keyword("Bias Mitigation", 0.75),
        Keyword("Fairness", 0.75),
        Keyword("Transparency", 0.7),
        Keyword("Accountability", 0.7)
    ],
    "Web Development": [
        # Core web dev languages and technologies (1.0)
        Keyword("HTML", 1.0),
        Keyword("CSS", 1.0),
        Keyword("JavaScript", 1.0),
        Keyword("TypeScript", 0.9),
        Keyword("React", 1.0),
        Keyword("Angular", 1.0),
        Keyword("Vue.js", 1.0),
        Keyword("Node.js", 1.0),
        Keyword("Express.js", 0.9),
        Keyword("Django", 1.0),
        Keyword("Flask", 0.9),
        Keyword("Ruby on Rails", 0.9),
        Keyword("PHP", 0.8),
        Keyword("Laravel", 0.8),
        Keyword("ASP.NET", 0.8),
        Keyword("jQuery", 0.7),

        # Frontend frameworks and libraries (0.8 - 1.0)
        Keyword("Bootstrap", 0.9),
        Keyword("Tailwind CSS", 0.9),
        Keyword("Sass", 0.8),
        Keyword("Webpack", 0.8),
        Keyword("Babel", 0.7),
        Keyword("Redux", 0.9),
        Keyword("Next.js", 0.9),
        Keyword("Gatsby", 0.8),
        Keyword("Material-UI", 0.8),
        Keyword("Styled Components", 0.8),

        # Backend technologies and concepts (0.8 - 1.0)
        Keyword("REST API", 1.0),
        Keyword("GraphQL", 0.9),
        Keyword("API Development", 1.0),
        Keyword("Microservices", 0.8),
        Keyword("Serverless", 0.7),
        Keyword("WebSockets", 0.7),
        Keyword("OAuth", 0.7),
        Keyword("JWT", 0.7),
        Keyword("JSON", 1.0),
        Keyword("XML", 0.6),
        Keyword("Database Design", 0.8),

        # Databases (0.7 - 1.0)
        Keyword("MySQL", 0.8),
        Keyword("PostgreSQL", 0.8),
        Keyword("MongoDB", 0.8),
        Keyword("Redis", 0.7),
        Keyword("SQLite", 0.7),
        Keyword("MariaDB", 0.6),

        # DevOps and infrastructure (0.6 - 0.8)
        Keyword("Docker", 0.8),
        Keyword("Kubernetes", 0.7),
        Keyword("CI/CD", 0.7),
        Keyword("Jenkins", 0.6),
        Keyword("Git", 1.0),
        Keyword("GitHub", 1.0),
        Keyword("GitLab", 0.9),
        Keyword("Bitbucket", 0.8),
        Keyword("AWS", 0.7),
        Keyword("Azure", 0.7),
        Keyword("Google Cloud", 0.7),
        Keyword("Nginx", 0.7),
        Keyword("Apache", 0.7),

        # Testing (0.6 - 0.8)
        Keyword("Jest", 0.8),
        Keyword("Mocha", 0.7),
        Keyword("Chai", 0.7),
        Keyword("Selenium", 0.7),
        Keyword("Cypress", 0.8),
        Keyword("Enzyme", 0.7),
        Keyword("Test-Driven Development", 0.8),
        Keyword("Unit Testing", 0.8),
        Keyword("Integration Testing", 0.7),

        # Tools and editors (0.5 - 0.8)
        Keyword("VS Code", 0.8),
        Keyword("Webpack", 0.8),
        Keyword("Chrome DevTools", 0.7),

        # Web security (0.6 - 0.8)
        Keyword("Cross-Site Scripting", 0.7),
        Keyword("CSRF", 0.7),
        Keyword("CORS", 0.7),
        Keyword("HTTPS", 0.8),
        Keyword("OWASP", 0.7),
        Keyword("Security Best Practices", 0.7),

        # Web performance and SEO (0.5 - 0.7)
        Keyword("PageSpeed", 0.6),
        Keyword("SEO", 0.7),
        Keyword("Web Accessibility", 0.7),
        Keyword("Responsive Design", 0.9),

        # Other related terms (0.3 - 0.6)
        Keyword("Progressive Web Apps", 0.7),
        Keyword("Single Page Applications", 0.8),
        Keyword("Mobile First Design", 0.7),
        Keyword("RESTful Services", 0.8),
        Keyword("Agile", 0.5),
        Keyword("Scrum", 0.5),
        Keyword("Kanban", 0.4),
    ],
    "Software Engineering": [
        # Core Programming Languages (1.0)
        Keyword("Java", 1.0),
        Keyword("Python", 1.0),
        Keyword("C++", 1.0),
        Keyword("C#", 1.0),
        Keyword("JavaScript", 0.9),
        Keyword("Ruby", 0.8),
        Keyword("Go", 0.8),
        Keyword("Scala", 0.7),
        Keyword("Swift", 0.7),
        Keyword("Kotlin", 0.7),
        Keyword("PHP", 0.6),
        Keyword("TypeScript", 0.8),
        Keyword("Objective-C", 0.6),
        Keyword("Perl", 0.5),

        # Software Development Methodologies (0.8 - 1.0)
        Keyword("Agile", 1.0),
        Keyword("Scrum", 1.0),
        Keyword("Kanban", 0.9),
        Keyword("Waterfall", 0.7),
        Keyword("Test-Driven Development", 0.9),
        Keyword("Behavior-Driven Development", 0.8),
        Keyword("Continuous Integration", 0.9),
        Keyword("Continuous Deployment", 0.9),
        Keyword("DevOps", 0.9),
        Keyword("Pair Programming", 0.7),

        # Software Design and Architecture (0.7 - 1.0)
        Keyword("Object-Oriented Programming", 1.0),
        Keyword("Functional Programming", 0.8),
        Keyword("Design Patterns", 1.0),
        Keyword("Microservices", 0.9),
        Keyword("RESTful APIs", 1.0),
        Keyword("Service-Oriented Architecture", 0.8),
        Keyword("SOLID Principles", 0.9),
        Keyword("Domain-Driven Design", 0.8),
        Keyword("Event-Driven Architecture", 0.7),
        Keyword("Clean Architecture", 0.8),
        Keyword("MVC", 0.8),
        Keyword("Multithreading", 0.8),
        Keyword("Concurrency", 0.8),

        # Tools and Environments (0.7 - 1.0)
        Keyword("Git", 1.0),
        Keyword("GitHub", 1.0),
        Keyword("GitLab", 0.9),
        Keyword("Bitbucket", 0.8),
        Keyword("Jenkins", 0.8),
        Keyword("Docker", 0.9),
        Keyword("Kubernetes", 0.8),
        Keyword("Visual Studio", 0.8),
        Keyword("IntelliJ IDEA", 0.8),
        Keyword("Eclipse", 0.7),
        Keyword("VS Code", 0.8),
        Keyword("Maven", 0.7),
        Keyword("Gradle", 0.7),
        Keyword("Ant", 0.6),

        # Testing Frameworks and Practices (0.7 - 0.9)
        Keyword("Unit Testing", 1.0),
        Keyword("Integration Testing", 0.9),
        Keyword("System Testing", 0.8),
        Keyword("Automated Testing", 0.9),
        Keyword("Selenium", 0.7),
        Keyword("JUnit", 0.8),
        Keyword("Mockito", 0.7),
        Keyword("Test Automation", 0.8),
        Keyword("Load Testing", 0.7),
        Keyword("Performance Testing", 0.7),

        # Software Development Concepts (0.7 - 1.0)
        Keyword("Algorithms", 1.0),
        Keyword("Data Structures", 1.0),
        Keyword("Code Reviews", 0.9),
        Keyword("Refactoring", 0.9),
        Keyword("Debugging", 1.0),
        Keyword("Memory Management", 0.7),
        Keyword("Performance Optimization", 0.8),
        Keyword("Version Control", 1.0),
        Keyword("Build Automation", 0.7),

        # Databases (0.6 - 0.8)
        Keyword("SQL", 0.8),
        Keyword("NoSQL", 0.7),
        Keyword("MongoDB", 0.7),
        Keyword("PostgreSQL", 0.7),
        Keyword("MySQL", 0.7),
        Keyword("Redis", 0.6),
        Keyword("Oracle", 0.6),

        # Cloud Platforms & Infrastructure (0.6 - 0.8)
        Keyword("AWS", 0.7),
        Keyword("Azure", 0.7),
        Keyword("Google Cloud", 0.7),
        Keyword("Serverless", 0.6),
        Keyword("Infrastructure as Code", 0.6),

        # Messaging & Integration (0.6 - 0.7)
        Keyword("RabbitMQ", 0.6),
        Keyword("Apache Kafka", 0.6),
        Keyword("REST API Development", 0.8),
        Keyword("SOAP", 0.6),

        # Soft Skills and Practices (0.5 - 0.7)
        Keyword("Problem Solving", 0.7),
        Keyword("Team Collaboration", 0.7),
        Keyword("Agile Coaching", 0.6)
    ],
    "Machine Learning": [
        # Core ML Concepts & Algorithms (1.0)
        Keyword("Machine Learning", 1.0),
        Keyword("Supervised Learning", 1.0),
        Keyword("Unsupervised Learning", 1.0),
        Keyword("Reinforcement Learning", 1.0),
        Keyword("Deep Learning", 1.0),
        Keyword("Neural Networks", 1.0),
        Keyword("Convolutional Neural Networks", 1.0),
        Keyword("CNN", 1.0),
        Keyword("Recurrent Neural Networks", 1.0),
        Keyword("RNN", 1.0),
        Keyword("Long Short-Term Memory", 1.0),
        Keyword("LSTM", 1.0),
        Keyword("Generative Adversarial Networks", 1.0),
        Keyword("GAN", 1.0),
        Keyword("Transformer Models", 1.0),
        Keyword("Attention Mechanism", 1.0),
        Keyword("BERT", 1.0),
        Keyword("GPT", 1.0),
        Keyword("Autoencoders", 0.9),
        Keyword("Support Vector Machines", 1.0),
        Keyword("SVM", 1.0),
        Keyword("Decision Trees", 1.0),
        Keyword("Random Forest", 1.0),
        Keyword("Gradient Boosting Machines", 1.0),
        Keyword("XGBoost", 1.0),
        Keyword("LightGBM", 0.9),
        Keyword("CatBoost", 0.9),
        Keyword("K-Nearest Neighbors", 0.9),
        Keyword("KNN", 0.9),
        Keyword("Naive Bayes", 0.9),
        Keyword("Clustering", 0.9),
        Keyword("K-Means Clustering", 0.9),
        Keyword("Hierarchical Clustering", 0.9),
        Keyword("DBSCAN", 0.8),
        Keyword("Principal Component Analysis", 0.9),
        Keyword("PCA", 0.9),
        Keyword("t-SNE", 0.8),
        Keyword("Dimensionality Reduction", 0.9),
        Keyword("Feature Engineering", 0.9),
        Keyword("Feature Selection", 0.8),
        Keyword("Cross-Validation", 0.9),
        Keyword("Hyperparameter Tuning", 0.9),
        Keyword("Grid Search", 0.8),
        Keyword("Random Search", 0.8),
        Keyword("Bayesian Optimization", 0.8),
        Keyword("Overfitting", 0.9),
        Keyword("Underfitting", 0.9),
        Keyword("Bias-Variance Tradeoff", 0.9),
        Keyword("Ensemble Learning", 0.9),
        Keyword("Bagging", 0.8),
        Keyword("Boosting", 0.9),
        Keyword("Stacking", 0.8),
        Keyword("Markov Decision Process", 0.8),
        Keyword("Q-Learning", 0.8),
        Keyword("Temporal Difference Learning", 0.7),

        # Programming Languages & Libraries (0.5 - 1.0)
        Keyword("Python", 0.8),
        Keyword("R", 0.6),
        Keyword("Julia", 0.5),
        Keyword("Scala", 0.4),
        Keyword("TensorFlow", 1.0),
        Keyword("PyTorch", 1.0),
        Keyword("Keras", 0.95),
        Keyword("scikit-learn", 1.0),
        Keyword("Pandas", 0.8),
        Keyword("NumPy", 0.8),
        Keyword("SciPy", 0.7),
        Keyword("Matplotlib", 0.7),
        Keyword("Seaborn", 0.7),
        Keyword("XGBoost", 1.0),
        Keyword("LightGBM", 0.9),
        Keyword("CatBoost", 0.9),
        Keyword("OpenCV", 0.7),
        Keyword("NLTK", 0.8),
        Keyword("SpaCy", 0.8),
        Keyword("Gensim", 0.7),
        Keyword("FastAI", 0.8),

        # Tools, Platforms & Environments (0.6 - 0.9)
        Keyword("Jupyter Notebook", 0.8),
        Keyword("Google Colab", 0.7),
        Keyword("MLflow", 0.8),
        Keyword("Kubeflow", 0.7),
        Keyword("TensorBoard", 0.7),
        Keyword("Docker", 0.7),
        Keyword("Kubernetes", 0.7),
        Keyword("AWS SageMaker", 0.7),
        Keyword("Google AI Platform", 0.7),
        Keyword("Azure Machine Learning", 0.7),
        Keyword("Apache Spark MLlib", 0.7),

        # Math & Stats (0.7 - 0.9)
        Keyword("Linear Algebra", 0.8),
        Keyword("Calculus", 0.7),
        Keyword("Probability", 0.8),
        Keyword("Statistics", 0.8),
        Keyword("Bayesian Statistics", 0.7),
        Keyword("Optimization", 0.8),
        Keyword("Gradient Descent", 0.8),
        Keyword("Convex Optimization", 0.7),
        Keyword("Markov Chains", 0.7),
        Keyword("Information Theory", 0.7),

        # Model Deployment & MLOps (0.6 - 0.8)
        Keyword("Model Deployment", 0.8),
        Keyword("MLOps", 0.8),
        Keyword("CI/CD", 0.7),
        Keyword("Continuous Integration", 0.7),
        Keyword("Continuous Deployment", 0.7),
        Keyword("API Development", 0.7),

        # Roles (0.7 - 0.9)
        Keyword("Machine Learning Engineer", 1.0),
        Keyword("Data Scientist", 0.9),
        Keyword("Research Scientist", 0.8),
        Keyword("Applied Scientist", 0.8)
    ],
    "Cyber Security": [
        # Core Concepts & Domains (1.0)
        Keyword("Cybersecurity", 1.0),
        Keyword("Information Security", 1.0),
        Keyword("Network Security", 1.0),
        Keyword("Application Security", 1.0),
        Keyword("Endpoint Security", 1.0),
        Keyword("Cloud Security", 1.0),
        Keyword("Identity and Access Management", 1.0),
        Keyword("IAM", 1.0),
        Keyword("Threat Intelligence", 1.0),
        Keyword("Incident Response", 1.0),
        Keyword("Vulnerability Management", 1.0),
        Keyword("Penetration Testing", 1.0),
        Keyword("Ethical Hacking", 1.0),
        Keyword("Risk Assessment", 1.0),
        Keyword("Security Operations Center", 1.0),
        Keyword("SOC", 1.0),
        Keyword("Security Information and Event Management", 1.0),
        Keyword("SIEM", 1.0),
        Keyword("Data Loss Prevention", 1.0),
        Keyword("DLP", 1.0),
        Keyword("Zero Trust", 1.0),
        Keyword("Cryptography", 1.0),
        Keyword("Encryption", 1.0),
        Keyword("Public Key Infrastructure", 1.0),
        Keyword("PKI", 1.0),

        # Protocols & Standards (0.9 - 1.0)
        Keyword("SSL", 1.0),
        Keyword("TLS", 1.0),
        Keyword("IPSec", 0.9),
        Keyword("HTTPS", 1.0),
        Keyword("SSH", 1.0),
        Keyword("OAuth", 1.0),
        Keyword("OpenID Connect", 0.9),
        Keyword("SAML", 0.9),
        Keyword("PCI DSS", 1.0),
        Keyword("HIPAA", 1.0),
        Keyword("GDPR", 1.0),
        Keyword("NIST", 1.0),
        Keyword("ISO 27001", 1.0),
        Keyword("CIS Controls", 0.9),

        # Security Tools & Technologies (0.8 - 1.0)
        Keyword("Firewalls", 1.0),
        Keyword("Intrusion Detection System", 1.0),
        Keyword("IDS", 1.0),
        Keyword("Intrusion Prevention System", 1.0),
        Keyword("IPS", 1.0),
        Keyword("Antivirus", 0.9),
        Keyword("Malware Analysis", 1.0),
        Keyword("SIEM Tools", 1.0),
        Keyword("Splunk", 1.0),
        Keyword("QRadar", 1.0),
        Keyword("Nessus", 1.0),
        Keyword("Metasploit", 1.0),
        Keyword("Burp Suite", 1.0),
        Keyword("Wireshark", 1.0),
        Keyword("Nmap", 1.0),
        Keyword("Kali Linux", 1.0),
        Keyword("Snort", 1.0),
        Keyword("OpenVAS", 0.9),
        Keyword("Tenable", 0.9),
        Keyword("CyberArk", 0.8),
        Keyword("Palo Alto Networks", 0.8),

        # Security Practices & Methodologies (0.8 - 1.0)
        Keyword("Pen Testing", 1.0),
        Keyword("Red Team", 1.0),
        Keyword("Blue Team", 1.0),
        Keyword("Purple Team", 0.9),
        Keyword("Threat Hunting", 1.0),
        Keyword("Forensics", 1.0),
        Keyword("Incident Management", 1.0),
        Keyword("Security Auditing", 0.9),
        Keyword("Patch Management", 0.9),
        Keyword("Security Awareness Training", 0.8),
        Keyword("Phishing Simulation", 0.8),
        Keyword("Vulnerability Scanning", 1.0),
        Keyword("Risk Management", 1.0),
        Keyword("Business Continuity", 0.8),
        Keyword("Disaster Recovery", 0.8),
        Keyword("Compliance Management", 1.0),

        # Authentication & Authorization (0.9 - 1.0)
        Keyword("Multi-Factor Authentication", 1.0),
        Keyword("MFA", 1.0),
        Keyword("Single Sign-On", 1.0),
        Keyword("SSO", 1.0),
        Keyword("Biometric Authentication", 0.8),

        # Programming & Scripting (0.6 - 0.9)
        Keyword("Python", 0.9),
        Keyword("PowerShell", 0.8),
        Keyword("Bash", 0.8),
        Keyword("JavaScript", 0.7),
        Keyword("C", 0.7),
        Keyword("C++", 0.7),

        # Cloud Security (0.8 - 1.0)
        Keyword("AWS Security", 1.0),
        Keyword("Azure Security", 1.0),
        Keyword("Google Cloud Security", 1.0),
        Keyword("Cloud Access Security Broker", 0.9),
        Keyword("CASB", 0.9),

        # Network Technologies (0.7 - 0.9)
        Keyword("VPN", 1.0),
        Keyword("Proxy", 0.8),
        Keyword("DNS Security", 0.8),
        Keyword("DDoS Mitigation", 1.0),

        # Certifications (1.0)
        Keyword("CISSP", 1.0),
        Keyword("CEH", 1.0),
        Keyword("CISA", 1.0),
        Keyword("CISM", 1.0),
        Keyword("CompTIA Security+", 1.0),
        Keyword("OSCP", 1.0),
        Keyword("GIAC", 1.0),
        Keyword("CRISC", 1.0),
        Keyword("CSSLP", 1.0),

        # Soft Skills & Other (0.5 - 0.8)
        Keyword("Security Policies", 0.8),
        Keyword("Communication Skills", 0.7),
        Keyword("Analytical Thinking", 0.8),
        Keyword("Problem Solving", 0.8),
        Keyword("Team Collaboration", 0.7),

        # Low relevance / unrelated (0.0)
        Keyword("Patent Filing", 0.0),
        Keyword("Microsoft Office", 0.0),
        Keyword("Customer Service", 0.0),
    ]
}
